export { default as HeroImg } from "./img/hero_image.png";
export { default as Group1 } from "./img/Group 1.png";
export { default as Group2 } from "./img/Group 2.png";
export { default as Product1 } from "./img/Product 1.png";
export { default as Product2 } from "./img/Product 2.png";
export { default as Product3 } from "./img/Product 3.png";
export { default as Product4 } from "./img/Product 4.png";
export { default as Product5 } from "./img/Product 5.png";
export { default as Product6 } from "./img/Product 6.png";
export { default as Product7 } from "./img/Product 7.png";
export { default as Product8 } from "./img/Product 8.png";
export { default as Product9 } from "./img/Product 9.png";
export { default as Product10 } from "./img/Product 10.png";
export { default as Product11 } from "./img/Product 11.png";
export { default as Product12 } from "./img/Product 12.png";
